// Generated by Finicky Kickstart
// Save as ~/.finicky.js

export default {
  defaultBrowser: "Google Chrome",
  //profile: "Profile 1"
  handlers: [
    {
      match: /^https?:\/\/bark\.us\/.*$/,
      browser: {
        name: "Google Chrome",
        profile: "Profile 1",
      },
    },
    {
      match: ({ opener }) =>
        ["Slack", "Microsoft Outlook"].includes(opener.name),
      browser: {
        name: "Google Chrome",
        profile: "Default",
      },
    },
    {
      match: /^https?:\/\/force\.com\/.*$/,
      browser: {
        name: "Google Chrome",
        profile: "Default",
      },
    },
    {
      match: /^https?:\/\/redhat\.com\/.*$/,
      browser: {
        name: "Google Chrome",
        profile: "Default",
      },
    },
  ],
}