// Generated by Finicky Kickstart
// Save as ~/.finicky.js

export default {
  defaultBrowser: {
    name: "Google Chrome",
    profile: "Jay - Home",
  },
  handlers: [
    {
      match: "www.bark.us/*",
      browser: {
        name: "Google Chrome",
        profile: "Jay - Home",
      },
    },
    {
      match: ({ opener }) =>
        ["Slack", "Microsoft Outlook"].includes(opener.name),
      browser: {
        name: "Google Chrome",
        profile: "Jay - Work",
      },
    },
    {
      match: [
        "*.salesforce.com/*",
        /^https?:\/\/redhat\.com\/.*$/,
      ],
      browser: {
        name: "Google Chrome",
        profile: "Jay - Work",
      },
    },
    // {
    //   match:
    //   browser: {
    //     name: "Google Chrome",
    //     profile: "Jay - Work",
    //   },
    // },
  ],
}

